### ISSUE TITLE
Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'xunit'

### ISSUE THREAD

**Issue by finkinfridom** [spekt/xunit.testlogger#63]
I have a GitLab pipeline that runs a `dotnet test --logger:"xunit;LogFilePath=results.xml"` command.

The tests run fine but I receive `Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'xunit'.` message and the `results.xml` file is empty `<assemblies timestamp="08/27/2024 09:06:35" />`.
The Visual Studio solution contains project both build for .NET framework 4.7.2 and netcore6.0.

I read the troubleshooting section and other issues here as well but nothing worked. What I tried so far:
- I added the `XunitXml.TestLogger` package to both my .NET framework and netcore tests projects
- I tried both the latest package version 4.0.254 and the previous 3.1.20 version but nothing changed
- I checked the `bin\Debug\net6.0` folder and I see `Spekt.TestLogger.dll` (but no `XunitXml.TestLogger` or similar DLLs)

Am I missing something?

**Comment by finkinfridom** [comment]
A couple of interesting finds:
1. it seems the .NET Framework project wasn't properly importing the `XunitXml.TestLogger.props` (similarly to what the `JunitXml.TestLogger` package was doing). Forced the nuget package reinstall and now it worked
2. The netcore6.0 project was including the `xunit.runner.console` package as well and it caused some incosistency/strange behavior as well into Visual Studio (tests were skipping without any reason).

Still having issue into the pipeline for the netcore6.0 project but checking for more information

**Comment by finkinfridom** [comment]
Running `dotnet test --diag:log.txt` I found this exception message

```
TpTrace Error: 0 : 1336, 4, 2024/08/29, 16:19:02.740, 13493737186173, vstest.console.dll, MulticastDelegateUtilities.SafeInvoke: 1: Invoking callback 3/Spekt.TestLogger.Core.TestRunBuilder for .InternalTestLoggerEvents.SendTestRunComplete, failed after 8 ms with: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'System.String Spekt.TestLogger.Core.TestResultInfo.get_DisplayName()'.
   at Microsoft.VisualStudio.TestPlatform.Extension.Xunit.Xml.TestLogger.XunitXmlSerializer.CreateTestElement(TestResultInfo result)
   at Microsoft.VisualStudio.TestPlatform.Extension.Xunit.Xml.TestLogger.XunitXmlSerializer.CreateCollection(IGrouping`2 resultsByType, List`1 testResultAsError)
   at Microsoft.VisualStudio.TestPlatform.Extension.Xunit.Xml.TestLogger.XunitXmlSerializer.<>c__DisplayClass9_0.<CreateAssemblyElement>b__2(IGrouping`2 resultsByType)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at Microsoft.VisualStudio.TestPlatform.Extension.Xunit.Xml.TestLogger.XunitXmlSerializer.CreateAssemblyElement(IGrouping`2 resultsByAssembly, LoggerConfiguration loggerConfiguration, TestRunConfiguration runConfiguration)
   at Microsoft.VisualStudio.TestPlatform.Extension.Xunit.Xml.TestLogger.XunitXmlSerializer.<>c__DisplayClass8_0.<CreateAssembliesElement>b__2(IGrouping`2 resultsByAssembly)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Microsoft.VisualStudio.TestPlatform.Extension.Xunit.Xml.TestLogger.XunitXmlSerializer.CreateAssembliesElement(List`1 results, LoggerConfiguration loggerConfiguration, TestRunConfiguration runConfiguration)
   at Microsoft.VisualStudio.TestPlatform.Extension.Xunit.Xml.TestLogger.XunitXmlSerializer.Serialize(LoggerConfiguration loggerConfiguration, TestRunConfiguration runConfiguration, List`1 results, List`1 messages)
   at Spekt.TestLogger.Core.TestRunCompleteWorkflow.Complete(ITestRun testRun, TestRunCompleteEventArgs completeEvent) in /home/runner/work/testlogger/testlogger/src/TestLogger/Core/TestRunCompleteWorkflow.cs:line 37
   at Spekt.TestLogger.Core.TestRunBuilder.<Subscribe>b__5_3(Object _, TestRunCompleteEventArgs eventArgs) in /home/runner/work/testlogger/testlogger/src/TestLogger/Core/TestRunBuilder.cs:line 55
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
```

Checking in the code where this issue is coming from

**Comment by finkinfridom** [comment]
Finally found out the root cause of the issue.
In our project we had to provide test results both as xunit and junit (the former for an internal tool, the latter for GitLab unit-test reporting purpose).
The projects had both the `JunitXml.TestLogger` and the `XunitXml.TestLogger` packages but they were **different versions**. Given they both share a common `Spekt.TestLogger` package, it may happen there were a reference to an incorrect version causing the `TestLogger` package failing in trying to access the `DisplayName` property (that wasn't available in an older version).

The solution is now easy (keeping both versions aligned) but may be helpful for somebody else in the future :)

**Comment by codito** [comment]
@finkinfridom thanks for sharing the investigation notes in detail. It will definitely help the community.

We've recently started shipping all the test loggers from a [single repo](https://github.com/spekt/testlogger), every logger will have the same release version, and the same snapshot of upstream dependency for the version. Hopefully, this will help reduce occurrences of this issue.
